name: golang lint

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  lint:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, 1.16.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
      